### ISSUE TITLE
what is psychtoolbox version for this program?

### ISSUE THREAD

**Issue by 200987299** [gabrielibagon/OpenBCI_MATLAB#2]
as the question

**Comment by gabrielibagon** [comment]
There is no Psychtoolbox requirement for running OpenBCI_MATLAB. If you're running into a problem with using OpenBCI with MATLAB and Psychtoolbox, specify your error and we might be able to help you if it involves some incompatibility with the OpenBCI_MATLAB interface (open a new issue if needed).
